# Generated by Django 5.0.2 on 2024-03-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0002_candidates_email_candidates_position_and_more'),
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EC_Admin.voters')),
            ],
        ),
    ]
