# Generated by Django 5.0.2 on 2024-03-27 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=244, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='candidate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
